Generate route with prefix
zeromicro/go-zero pull request #1200
Opened 2021-11-02 13:09 UTC by anqiansong

* Supported route generates with prefix

2021-11-02 13:21 UTC, kevwan requested changes

2021-11-02 13:21 UTC, kevwan commented on tools/goctl/api/tsgen/gen.go
> +	for _, g := range service.Groups {
duplicated code?

2021-11-02 13:21 UTC, kevwan commented on tools/goctl/util/string.go
> +func TrimSpace(s string) string {
strings.TrimSpace?

2021-11-02 13:23 UTC, anqiansong commented on tools/goctl/api/tsgen/gen.go
> +	for _, g := range service.Groups {
see spec.Service.JoinPrefix

2021-11-02 13:26 UTC, anqiansong commented on tools/goctl/util/string.go
> +func TrimSpace(s string) string {
Done.

2021-11-02 13:52 UTC, kevwan commented on tools/goctl/api/ktgen/cmd.go
> +	api.Service = service
api.Service = api.Service.JoinPrefix()

2021-11-03 06:08 UTC, kevwan requested changes

2021-11-03 06:08 UTC, kevwan commented on tools/goctl/api/dartgen/gen.go
> +	api.Service= api.Service.JoinPrefix()
format code

2021-11-03 06:08 UTC, kevwan commented on tools/goctl/api/javagen/gen.go
> +	api.Service= api.Service.JoinPrefix()
format

2021-11-03 12:56 UTC, kevwan approved these changes

2021-11-03 12:57 UTC, merged